# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help test this project

name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Test
      run: python -m tox -e py
  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Fetch bandit
      uses: actions/checkout@v3
      with:
        repository: johnnytaira/python-bandit-action
        ref: action
        path: .github/actions/python-bandit-action
    - name: Run bandit action 
      uses: ./.github/actions/python-bandit-action

    


